<a href="https://colab.research.google.com/github/kwansawanth/python_dataviz2023/blob/main/Basic_Programming_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Functions ($f(x) = y$)

```python
def function_name(input_x):
    # do something with input_x to get output_y
    return output_y
```
def = นิยามของฟังก์ชัน

$f_1(x)=x^2 + 75$

In [3]:
def function_f1(x):
    a = x**2   # ** = ยกกำลัง2
    y = a + 75
    return y
# codeที่เยื้องเป็นส่วนนหนึ่งของบรรทัดบนที่ไม่เยื้อง code
#print('done!')

# code ที่อยู่ลำดับเดียวกันมีความสำคัญเท่ากัน

In [ ]:
function_f1(3)

84

function มีส่วนสำคัญทั้งหมด 4 ส่วน

1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร  `def function_name()`: (ขาดไม่ได้)
2. กำหนดตัวแปรที่จะเป็น input  _Input_ (ขาดได้)
3. ส่วนประมวลผล do_something with _Input_ to get _Output_ (ขาดไม่ได้)
4. ส่วน output `return` _Output_(ขาดได้)

### ตัวอย่าง function ที่มีส่วนประกอบครบ


In [ ]:
def function_f1(x):
    a = x**2
    y = a + 75
    return y

### ตัวอย่าง function ที่ ไม่มี input
ทำงานเหมือนเดิมตลอด ค่าไม่เปลี่ยนแปลง

In [ ]:
def pi_v():
    y = 3.14159265359
    return y

In [ ]:
#หาพท.วงกลม รัศมี = 2/// สูตร  pi r^2   ผลลัพธ์เหมือนเดิม
piv = pi_v()
circle_area_r2 = piv*(2**2)
print(circle_area_r2)

12.56637061436


### Function ไม่มี process ไม่ได้

In [ ]:
def function_a():

SyntaxError: ignored

ตัวอย่าง Function ที่ไม่มี output

In [ ]:
def print_name_id(name,id):
    print(f'ชื่อ {name} รหัสประจำตัว {id}') #กระบวนการว่าให้เเสดง ชื่อ

In [ ]:
print_name_id('ณัฐธิดา','623020435-1')

ชื่อ ณัฐธิดา รหัสประจำตัว 623020435-1


In [ ]:
a = print_name_id('ณัฐธิดา','623020435-1')

ชื่อ ณัฐธิดา รหัสประจำตัว 623020435-1


In [ ]:
a # เป็นช่องว่างเพราะ ไม่มีการ  return  ค่า

print()  ใส่ input ได้หลายตัว
-   ** คือ จำเป็นต้องใส่
- = คือ ไม่จำเป็นต้องใส่ มีค่าตั้งต้นมาให้
- end คือ จบบรรทัด  \n คือด้วยการขึ้นบรรทัดใหม่
- sep คือ เว้นวรรคค่าด้วย ' ' คือ ช่องว่าง

In [ ]:
print('ณัฐธิดา')
print('623020435-1')

ณัฐธิดา
623020435-1


In [ ]:
print('ณัฐธิดา',end='->')  # end =  จบบรรทัดด้วย
print('623020435-1')

ณัฐธิดา->623020435-1


In [ ]:
print('ณัฐธิดา','623020435-1') # ว่าง sep= ไว้ เลยเป็นช่องว่าง

ณัฐธิดา 623020435-1


In [ ]:
print('ณัฐธิดา','623020435-1',sep=' & ') # sep= กำหนดค่า = &

ณัฐธิดา & 623020435-1


## input ของ function แบ่งเป็น 2 ชนิด (จำเป็นต้องใส่ กับ ไม่จำเป็นต้องใส่)

ตัวอย่าง function `print_grade()` มี input 3 ตัว จำเป็นต้องใส่ 2 ตัว คือ name กับ id และไม่จำเป็นต้องใส่ 1 ตัว คือเกรด ซึ่งมีค่า default เป็น F

In [ ]:
def print_grade(name,id,grade = 'F'):
    print(f'รหัสประจำตัว {id} ชื่อ {name}')   # process ให้แสดง รหัส และชื่อ
    print(f'ได้เกรด {grade}') # process

In [ ]:
print_grade('นายสิทธัตกะ จรัสแสง','623020541-2')

รหัสประจำตัว 623020541-2 ชื่อ นายสิทธัตกะ จรัสแสง
ได้เกรด F


In [ ]:
print_grade('นายสิทธัตกะ จรัสแสง','623020541-2','A')

รหัสประจำตัว 623020541-2 ชื่อ นายสิทธัตกะ จรัสแสง
ได้เกรด A


In [ ]:
print_grade(id='623020541-2',name='นายสิทธัตกะ จรัสแสง',grade='B+')  #กรณีที่มีตัวแปรเยอะ จำลำดับไม่ได้ ก็ระบุไปเลย

รหัสประจำตัว 623020541-2 ชื่อ นายสิทธัตกะ จรัสแสง
ได้เกรด B+


# Looping (for)
สำหรับทำงานเยอะๆ ซ้ำๆ

```python
for member in listEx:       ## วนที่สมาชิก ใน list
    do_something()
```
for ชื่อตัวแปร in list ที่จะเอามาใช้เป็นสมาชิกใน ตัวแปร:     
    
วนซ้ำ
- วนซ้ำสมาชิกใน



In [ ]:
for member in [1,2,3,4,5,6]:
    print(member)

1
2
3
4
5
6


In [ ]:
def print_name(name):   # name input รอรับ
    print(f'ฉันชื่อ {name}') # กบก

In [ ]:
for name in ['วัชราภรณ์','จุฑากาญจน์ ','ชลธิชา','ญาดา','กิตติคุณ']:  # ชื่อ name(ตัวแปร ที่จะไปดึงเอาสมาชิกเเต่ละตัวมาใช้ใน loop ) ที่เอาไปเป็น input
    print_name(name) #จะไปเป็น input ของด้านบน

ฉันชื่อ วัชราภรณ์
ฉันชื่อ จุฑากาญจน์ 
ฉันชื่อ ชลธิชา
ฉันชื่อ ญาดา
ฉันชื่อ กิตติคุณ


In [ ]:
list_name_id_grade = [['นางสาวเบญญาภา ระภูเขียว','623020527-6','B'],
                      ['นางสาวทักษิณา ราชหุ่น','623021000-1','A'],
                      ['นางสาวปลายฟ้า คำเพ็ง','623021005-1','C']]

In [ ]:
for each in list_name_id_grade:
    name = each[0] #สามาชิกตัวแรกของสมาชิกอันเเรกของอันใหญ่
    id = each[1]
    grade = each[2]
    print_grade(name,id,grade)
    print('----------------')

รหัสประจำตัว 623020527-6 ชื่อ นางสาวเบญญาภา ระภูเขียว
ได้เกรด B
----------------
รหัสประจำตัว 623021000-1 ชื่อ นางสาวทักษิณา ราชหุ่น
ได้เกรด A
----------------
รหัสประจำตัว 623021005-1 ชื่อ นางสาวปลายฟ้า คำเพ็ง
ได้เกรด C
----------------


## ใช้ for loop เพิ่มสมาชิกใน list  *****

In [ ]:
#อยากได้ข้อมูลแยกกัน ชื่ออย่างเดียว/รหัสอย่างเดียว/เกรดอย่างเดียว
list_name = [] #นิยมสร้าง list เปล่าๆก่อน
list_id = []
list_grade = []
for each in list_name_id_grade:
    list_name.append(each[0])
    list_id.append(each[1])
    list_grade.append(each[2])

In [ ]:
list_name

['นางสาวเบญญาภา ระภูเขียว', 'นางสาวทักษิณา ราชหุ่น', 'นางสาวปลายฟ้า คำเพ็ง']

In [ ]:
list_id

['623020527-6', '623021000-1', '623021005-1']

In [ ]:
list_grade

['B', 'A', 'C']

### การวนลูปด้วย `range()`

- สร้าง list 0 - ก่อนเลขนั้น
- วนลูปแบบซ้ำๆ ไม่ต้องการเปลี่ยนแปลงอะไร

In [ ]:
for i in range(100):
    print('งง', end = ' ')

งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง งง 

In [ ]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
list(range(5,20)) # เริ่มจาก 5 ก่อน 20

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

### Loop ซ้อน Loop (nested loop)


In [ ]:
#แม่สูตรคูณ
for mem1 in range(2,5): #แม่[2,3,4]
    print(f'now mem1 = {mem1}')
    for mem2 in range(1,13): #[1,2,3,4,5,6,7,8,9,10,11,12]ตัวมาคูณ
        print(f'{mem1} x {mem2} = {mem1*mem2}')
    print(f'end inner for mem1 = {mem1}') #จบในลูป

now mem1 = 2
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
2 x 11 = 22
2 x 12 = 24
end inner for mem1 = 2
now mem1 = 3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
3 x 11 = 33
3 x 12 = 36
end inner for mem1 = 3
now mem1 = 4
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
4 x 11 = 44
4 x 12 = 48
end inner for mem1 = 4


### Loop in Function

In [ ]:
def print_grade_loop(names,grades): # names,grades มีหลายสมาชิก เป็นlist
    for n,g in zip(names,grades): # The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.
        print(f'{n} ได้เกรด {g}')  #  zip การจับคู่ ของเเต่ละ list ในตำแหน่เดียวกัน // จับ 2 list มาร่วมกัน

In [ ]:
print_grade_loop(list_name,list_grade)

นางสาวเบญญาภา ระภูเขียว ได้เกรด B
นางสาวทักษิณา ราชหุ่น ได้เกรด A
นางสาวปลายฟ้า คำเพ็ง ได้เกรด C


# HW2.5 สร้าง function print logo พรรคก้าวไกล โดย input พื้นหลังได้

In [1]:
import numpy as np
bg = 0
pbg = bg * np.ones((25,18))
gg = 11
pbg[1,1:20] = gg
pbg[2,1:20] = gg
pbg[3,1:20] = gg
pbg[4,16:20] = gg
pbg[5,15:19] = gg
pbg[6,14:18] = gg
pbg[7,13:17] = gg
pbg[8,12:16] = gg
pbg[9,11:15] = gg
pbg[10,10:14] = gg
pbg[11,9:13] = gg
pbg[12,8:12] = gg
pbg[13,7:11] = gg
pbg[14,6:10] = gg
pbg[15,5:9] = gg
pbg[16,4:8] = gg
pbg[17,3:7] = gg
pbg[18,2:6] = gg
pbg[5,1:12] = gg
pbg[6,1:11] = gg
pbg[7,8:10] = gg
pbg[8,7:9] = gg
pbg[9,6:8] = gg
pbg[10,5:7] = gg
pbg[11,4:6] = gg
pbg[12,3:5] = gg
pbg[13,2:4] = gg
pbg[14,1:3] = gg



print(pbg)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [ 0. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [ 0. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 11. 11.]
 [ 0. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.  0.  0.  0. 11. 11. 11.]
 [ 0. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.  0.  0.  0. 11. 11. 11. 11.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 11. 11.  0.  0.  0. 11. 11. 11. 11.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 11. 11.  0.  0.  0. 11. 11. 11. 11.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 11. 11.  0.  0.  0. 11. 11. 11. 11.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 11. 11.  0.  0.  0. 11. 11. 11. 11.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 11. 11.  0.  0.  0. 11. 11. 11. 11.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 11. 11.  0.  0.  0. 11. 11. 11. 11.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 11. 11.  0.  0.

# Conditional Statement (if)

```python
if condition1:
    do_something() ## ถ้า condition1 เป็นจริง ทำ do_something()
elif condition2:
    do_another_thing()  ## ถ้า condition1 ไม่เป็นจริงแต่ condition2 เป็นจริง ทำ do_another_thing()
else:
    do_the_last_thing() ## ถ้าไม่มี condition ไหนเป็นจริงเลย ทำ do_the_last_thing()
```

In [ ]:
for n in list_name:
    if len(n)>20:  #ถ้าจำนวนชื่อมีตัวอักสร มากกว่า 20 ตัวอักษร
        print(f'{n} ได้เกรด A')
    else:
        print(f'{n} ได้เกรด F')

นางสาวเบญญาภา ระภูเขียว ได้เกรด A
นางสาวทักษิณา ราชหุ่น ได้เกรด A
นางสาวปลายฟ้า คำเพ็ง ได้เกรด F


### operator ที่ใช้ตรวจสอบ condition

== (เท่ากับ) , != (ไม่เท่ากับ), >=, <=, <, >, and, or
- ผลลัพธ์มีแค่ Ture flase

In [ ]:
a = 10 == 20
print(a)

False


In [ ]:
b = 15 <= 20
print(b)

True


In [ ]:
b = (15 <= 20) and (10==20)
print(b)

False


In [ ]:
if a:             # a เป็น false ก็เลยไม่แสดงค่า
    print('x')

In [ ]:
if True:
    print('x')

x


In [ ]:
if a and b:
    print('x')

In [ ]:
if a or b:
    print('x')

# HW
เขียน function ตัดเกรด โดยที่ input เป็นคะแนน(0-100) , output เป็นเกรด (F-A) หรือ 'ไม่สามารถตัดเกรดได้'

วนลูปตัดเกรด input = [1,50,65,90,101,-5,49,'ก',80]

กำหนด

*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ  0  แต่น้อยกว่า 50 จะได้เกรด F
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 50 แต่น้อยกว่า 55 จะได้เกรด D
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 55 แต่น้อยกว่า 60 จะได้เกรด D+
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 60 แต่น้อยกว่า 65 จะได้เกรด C
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 65 แต่น้อยกว่า 70 จะได้เกรด C+
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 70 แต่น้อยกว่า 75 จะได้เกรด B
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 75 แต่น้อยกว่า 80 จะได้เกรด B+
*  ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 80  จะได้เกรด A
*  ถ้าคะแนนไม่อยู่ในช่วง 0-100 ให้ return 'ไม่สามารถตัดเกรดได้'

In [ ]:
input = [1,50,65,90,101,-5,49,'ก',80]

In [ ]:
'ก' is not int()

True

In [ ]:
type('')

str

func ควรแยกกับ for

In [ ]:
def grading(x):
    if type(x) is int:     # type(x) ตรวจสอบชนิดของตัวแปร
        if x < 0:
            y =f'คะแนน {x} ไม่สามารถตัดเกรดได้'
        elif x < 50:
            y = f'คะแนน {x} ได้เกรด F'
        elif x < 55:
            y = f'คะแนน {x} ได้เกรด D'
        elif x < 60:
            y = f'คะแนน {x} ได้เกรด D+'
        elif x < 65:
            y = f'คะแนน {x} ได้เกรด C'
        elif x < 70:
            y = f'คะแนน {x} ได้เกรด C+'
        elif x < 75:
            y = f'คะแนน {x} ได้เกรด B'
        elif x < 80:
            y = f'คะแนน {x} ได้เกรด B+'
        elif x <= 100:
            y = f'คะแนน {x} ได้เกรด A'
        else:
            y =f'คะแนน {x} ไม่สามารถตัดเกรดได้'
    else:
        y =f'คะแนน {x} ไม่สามารถตัดเกรดได้'

    return y

In [ ]:
type(1) is int

True

In [ ]:
grading(1)

'คะแนน 1 ได้เกรด F'

In [ ]:
for i in input:
    print(grading(i))

คะแนน 1 ได้เกรด F
คะแนน 50 ได้เกรด D
คะแนน 65 ได้เกรด C+
คะแนน 90 ได้เกรด A
คะแนน 101 ไม่สามารถตัดเกรดได้
คะแนน -5 ไม่สามารถตัดเกรดได้
คะแนน 49 ได้เกรด F
คะแนน ก ไม่สามารถตัดเกรดได้
คะแนน 80 ได้เกรด A
